import { Fragment, useState } from "react";
import AboutModal from "./AboutModal";
import classes from "./Header.module.css";
import RulesModal from "./RulesModal";

const Header = () => {
  const [rulesModalIsOpen, setRulesModalIsOpen] = useState(false);
  const [aboutModalOpen, setAboutModalOpen] = useState(false);
  return (
    <Fragment>
      <div className={classes.navbar_body}>
        <div className={classes.logo}>
          <img src="../public/Game_logo.png" alt="" />
        </div>
        <div className={classes.navbar_list}>
          <h2
            onClick={() => {
              setRulesModalIsOpen(true);
            }}
          >
            Game Rules
          </h2>

          <RulesModal
            open={rulesModalIsOpen}
            onClose={() => {
              setRulesModalIsOpen(false);
            }}
          >
            <h3>Game Rules</h3>
            <p>This is a classic Mastermind game.</p>
            <p>
              When you click the 'New Game' button the computer selects 4 colors
              from the possible 6 colors and arranges them in a random order.
              (Colors can occure more than once)
            </p>
            <p>
              The possible available 6 colors are the following:
              <span className={classes.green}> Green </span>
              <span className={classes.yellow}>Yellow </span>
              <span className={classes.red}>Red </span>
              <span className={classes.brown}>Brown </span>
              <span className={classes.pink}>Pink </span>
              <span className={classes.blue}>Blue </span>
            </p>
            <p>
              An example order, which can happen when you hit the 'New Game'
              button: <span className={classes.green}> Green </span>
              <span className={classes.yellow}>Yellow </span>
              <span className={classes.green}>Green </span>
              <span className={classes.brown}>Brown </span>
            </p>
            <p>Your goal is to find out the order generated by the computer!</p>
            <p>
              On the left side you can see a container with 6 rows with empty
              slots. You can pick a color from the container on the right, and
              fill it into the left container by clicking.
            </p>
            <p>
              Once you filled in your row you can click the 'submit' button.
              After that a container may appear with different colored dots.
              White dots indicate that one of the colors in your order is indeed
              part of the original order, but in an other slot. Black dots
              indicate that one of your colors is in the original order and it
              is at the right place. The spreading of white and black dots are
              completely random and not connected to the slot order.
            </p>
            <p>Happy Gaming!</p>
          </RulesModal>
          <h2
            onClick={() => {
              setAboutModalOpen(true);
            }}
          >
            About
          </h2>
          <AboutModal
            open={aboutModalOpen}
            onClose={() => {
              setAboutModalOpen(false);
            }}
          >
            <h3>About</h3>
            <p>This project was created by React.</p>
            <p>Current version: 1.0</p>
            <p>
              Make sure to check some of works on the pages at the bottom of
              this site.
            </p>
          </AboutModal>
          <p>v1.0</p>
        </div>
      </div>
    </Fragment>
  );
};

export default Header;
